# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14dbe8846c083af6e091a6aadc9ab9153f25cf8771d2658291a49120c26a0fc2011c5f43242e9f54f22c1d3cdccf64ff05c34660b81da61ec99f9a13ac9aa9a1

test:
  secret_key_base: 7e4b2ab99ec1eaef9b4163cc0e17fba0de0760e3254019f58fa584ccdc1ba3310195053df2048e12fccba45e8187d686aa25710ae6ffe381cef26296434c8097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
